### ISSUE TITLE
Team names and colors

### ISSUE THREAD

**Issue by kostajh** [durhamatletico/durhamatletico.github.io#12]
- Mattie B's
- Motorco FC
- McCabe's
- Durham All Stars
- Market Failure
- TBD

**Comment by kostajh** [comment]
@davidfellerath could you contact each pub and ask them what colors they want? Maybe do a group email, so people can reply all. All Stars can be yellow.

**Comment by davidfellerath** [comment]
Will do. Will also get captain contacts.
