### ISSUE TITLE
Create Durham Atletico Facebook Page

### ISSUE THREAD

**Issue by kostajh** [durhamatletico/durhamatletico.github.io#18]
I don't use Facebook, so over to you @davidfellerath :-)

**Comment by davidfellerath** [comment]
Ok, I'm on it. I may see if Geoff wants to be the administrator.

**Comment by kostajh** [comment]
@davidfellerath can you post the URL please so I can link it on the site?

**Comment by davidfellerath** [comment]
I have started a Facebook page. The information is largely populated but I need graphics. I have put emails out to a couple of people. I will work on this.

**Comment by kostajh** [comment]
@davidfellerath page is linked on site.
