### ISSUE TITLE
Test the registration process

### ISSUE THREAD

**Issue by davidfellerath** [durhamatletico/durhamatletico.github.io#20]
After you put on the button, check to see if you can pay through it. I linked it to the bank account, but it may take a couple of days. There is an instant confirmation option that I wasn't able to get to work, so we may have to settle for the slower method. Still, it's worth trying Friday to see if we can process payments through it.

**Comment by kostajh** [comment]
Seems like $90 is hard coded as the only option?

**Comment by davidfellerath** [comment]
Let me see if I can tweak that to allow flexible payment. 

What if we say: "We have budgeted this league for $90 a player. This will allow us to pay our expenses and purchase goals we need in the spring. However, we don't want anyone to be turned away for lack of funds. If this is an issue, please pay what you can afford."

**Comment by kostajh** [comment]
sounds good!
davidfellerath writes:

> Let me see if I can tweak that to allow flexible payment. 
>
> What if we say: "We have budgeted this league for $90 a player. This will allow us to pay our expenses and purchase goals we need in the spring. However, we don't want anyone to be turned away for lack of funds. If this is an issue, please pay what you can afford."
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/durhamatletico/durhamatletico.github.io/issues/20#issuecomment-71205612

-- 
kostaharlan.net | @kostajh

**Comment by davidfellerath** [comment]
I have updated this copy at #21

**Comment by kostajh** [comment]
@davidfellerath thanks. I renamed this issue to "Test the registration process". I'll test registering, but I'll ask someone from our team to go to durhamatletico.com and see if they can register without problems, and get feedback from them on the process.
