### ISSUE TITLE
Build out registration page

### ISSUE THREAD

**Issue by kostajh** [durhamatletico/durhamatletico.github.io#21]
@davidfellerath let me know what you think: durhamatletico.com/register

**Comment by davidfellerath** [comment]
First, on the home page, can you fix the bad break so "Jan.30!" doesn't fall on the next line?

1. Cut "We need to collect some info about you. Fill out this form here."  It's redundant and sounds a bit like the NSA. ;-) I think it's better just to make the headline linkable.

2. Cut "Next, you need to pay the $90 registration fee via PayPal. You don't need a PayPal account to do so you can use your credit card." 

3. Replace with "We have budgeted this league for $90 a player. This will allow us to pay our expenses and purchase goals we need in the spring. However, we don't want anyone to be turned away for lack of funds. If this is an issue, please pay what you can afford. We accept credit cards here. We'd prefer that you pay here, but you can also pay with cash, check or credit card onsite. [LINK TO THIS: You may pay here]."
