### ISSUE TITLE
Head injury action plan

### ISSUE THREAD

**Issue by kostajh** [durhamatletico/durhamatletico.github.io#26]
sub issue from #9

**Comment by kostajh** [comment]
My view is, if you have a head injury, you stop playing, end of story. If you agree @davidfellerath we should advise refs of this rule. It could be a majority decision made between team captain of player who is injured, the player, and the ref.

**Comment by davidfellerath** [comment]
Agreed

**Comment by davidfellerath** [comment]
Text for section of Futsal League page called "Concussion policy."

We want our games to be as safe as possible, and dangerous play will not be allowed. That said, our insurance policy requires us to have the following policy regarding concussions:

If a player suffers a head injury that leads the referee to believe he or she may have concussed, the player will be removed from the game until its conclusion. The referee may choose to consult with the team captains about the severity of the injury, but his or her decision about the player's fitness is final.

The referee will note the incident and the player's identity on the match report. Before returning to play in subsequent weeks, the player must produce written clearance from a licensed physician.

We hope no one is injured playing in the Durham Atletico futsal league. However, injuries do occur, and this policy will be strictly enforced.
