### ISSUE TITLE
Need to locate blog post of 9/3 and publish

### ISSUE THREAD

**Issue by davidfellerath** [durhamatletico/durhamatletico.github.io#31]
I made a mess of trying to blog. You should see a saved draft in a folder called "2015." The mistake I made was failing to create a proper file path (specifically I botched the date of the post).

In trying to fix this I also created another new post. This should be deleted.

**Comment by kostajh** [comment]
fixed! http://durhamatletico.com/2015/09/04/about-sherwood-park.html

davidfellerath writes:

> I made a mess of trying to blog. You should see a saved draft in a folder called "2015." The mistake I made was failing to create a proper file path (specifically I botched the date of the post).
>
> In trying to fix this I also created another new post. This should be deleted.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/durhamatletico/durhamatletico.github.io/issues/31

-- 
kosta@kostaharlan.net
