### ISSUE TITLE
To do before we announce a start date:

### ISSUE THREAD

**Issue by davidfellerath** [durhamatletico/durhamatletico.github.io#8]
Here's what we need to have ready before we announce a Feb 3 start:

* Goals and balls (no word yet from Malachy on his efforts to secure discount from Eurosport)
* referees (I have written Rob)
* Names of our teams, their colors and a schedule
* medical waiver ready for them to sign
* match reports for referees to use
* Insurance paid and gym deposit made (should have this finished by early next week)
* anything else?

**Comment by kostajh** [comment]
Made issues for all of these. Check out https://github.com/durhamatletico/durhamatletico.github.io/labels/launch%20blocker
