### ISSUE TITLE
Logistical issues

### ISSUE THREAD

**Issue by davidfellerath** [durhamatletico/durhamatletico.github.io#9]
* We need a logistics committee: I nominate Kosta, David, JD, and my friend (and your future friend) Sergio 
* We need to meet next week, go over logistics, to make sure we pull off first night without a hitch, from having all the gear we need to set-up and break-down.
* Make sure we have a head-injury action plan
* Make a game-day checklist. Things to include are:
  1. setup routine and gear check list (don't forget air pump)
   2. confirm referee
   3. have roster sheets and medical waivers ready. Roster sheets will be used to make sure players have paid
   4. receipt book for players paying in person
   5. etc

**Comment by kostajh** [comment]
Made sub issue for #17

**Comment by davidfellerath** [comment]
Have invited Cheko and JD to be on the logistics committee.
